--- 
- 
  auth: 
    aws_access_key: AWS_ACCESS_KEY_ID
    aws_secret_key: AWS_SECRET_ACCESS_ID
  gather_facts: false
  hosts: localhost
  name: "Create Ec2 instances"
  tasks: 
    - 
      block: 
        - 
          ec2_instance_info: ~
          name: "Get Running instance Info"
          register: ec2info
        - 
          debug: var="ec2info.instances"
          name: "Print info"
      name: "Get info block"
      tags: 
        - always
        - getinfoonly
